export const GENERATE_NEW_ARRAY = 'GENERATE_NEW_ARRAY';
export const SET_SIZE = 'SET_SIZE';
export const SET_SELECTED_ALGORITHM = 'SET_SELECTED_ALGORITHM';
export const SET_IS_SORTING = 'SET_IS_SORTING';
export const UPDATE_ARRAY = 'UPDATE_ARRAY';
